adding transform_alignments
fnothaft/toil-adam pull request #8
Opened 2017-05-08 21:39 UTC by heuermh

Hacked up `adam_pipeline/preprocessing.py` for this, which downloads, converts, and uploads. Early PR for feedback and because I don't remember how to build or run this stuff.

2017-05-09 20:34 UTC, fnothaft requested changes
Few small nits. If you've got time after the BDG call tomorrow, perhaps I can get you up to speed on running it?

2017-05-09 20:34 UTC, fnothaft commented on src/toil_bdg/transform_alignments/transform_alignments.py
> +def remove_file(master_ip, filename, spark_on_toil):
You can import this from `toil_bdg.adam_pipeline.preprocessing`

2017-05-09 20:34 UTC, fnothaft commented on src/toil_bdg/transform_alignments/transform_alignments.py
> +def remove_file(master_ip, filename, spark_on_toil):
Ditto to `truncate_file`, `upload_data`, and `download_data`

2017-09-01 14:28 UTC, heuermh commented
Closing as WontFix

2017-09-01 14:28 UTC, closed without merging